id {
  package: "com.example"
  name: "wiggle_joint_py"
}
display_name: "Wiggle joint"
vendor {
  display_name: "Intrinsic"
}
documentation {
  description: "Moves one joint on a robot back and fourth 5 degrees."
}
options {
  supports_cancellation: false
  python_config {
    skill_module: "skills.wiggle_joint.wiggle_joint"
    proto_module: "skills.wiggle_joint.wiggle_joint_pb2"
    create_skill: "skills.wiggle_joint.wiggle_joint.WiggleJoint"
  }
}
dependencies {
  required_equipment {
    key: "robot"
    value {
      capability_names: "Icon2Connection"
      capability_names: "Icon2PositionPart"
    }
  }
}
parameter {
  message_full_name: "com.example.WiggleJointParams"
}
