id {
  package: "com.example"
  name: "scan_barcodes_py"
}
vendor {
  display_name: "Intrinsic"
}
documentation {
  doc_string: "Skill that connects to a camera resource and scans all visible barcodes using OpenCV."
}
options {
  supports_cancellation: false
  python_config {
    skill_module: "skills.scan_barcodes.scan_barcodes"
    proto_module: "skills.scan_barcodes.scan_barcodes_pb2"
    create_skill: "skills.scan_barcodes.scan_barcodes.ScanBarcodes"
  }
}
dependencies {
    required_equipment {
    key: "camera"
    value {
      equipment_type_names: "CameraConfig"
    }
  }
}
parameter {
  message_full_name: "com.example.ScanBarcodesParams"
}
return_type {
  message_full_name: "com.example.ScanBarcodesResult"
}
