id {
  package: "com.example"
  name: "use_world_cc"
}
display_name: "Use world"
vendor {
  display_name: "Intrinsic"
}
documentation {
  description: "Queries information from the world and makes some world updates."
}
options {
  supports_cancellation: false
  cc_config {
    create_skill: "::use_world::UseWorld::CreateSkill"
  }
}
dependencies {
  required_equipment {
    key: "camera"
    value {
      capability_names: "CameraConfig"
    }
  }
  required_equipment {
    key: "robot"
    value {
      capability_names: "Icon2Connection"
      capability_names: "Icon2PositionPart"
    }
  }
}
parameter {
  message_full_name: "com.example.UseWorldParams"
}
