id {
  package: "com.example"
  name: "start_stopwatch"
}
display_name: "Start Stopwatch"
vendor {
  display_name: "Intrinsic"
}
documentation {
  description: "Starts a stopwatch."
}
options {
  supports_cancellation: false
  python_config {
    skill_module: "skills.start_stopwatch.start_stopwatch"
    proto_module: "skills.start_stopwatch.start_stopwatch_pb2"
    create_skill: "skills.start_stopwatch.start_stopwatch.StartStopwatch"
  }
}
dependencies {
  required_equipment {
    key: "stopwatch_service"
    value {
      capability_names: "stopwatch.StopwatchService"
    }
  }
}
parameter {
  message_full_name: "com.example.StartStopwatchParams"
  default_value {
    type_url: "type.googleapis.com/com.example.StartStopwatchParams"
  }
}
