id {
  package: "com.example"
  name: "stop_stopwatch"
}
display_name: "StopStopwatch Python"
vendor {
  display_name: "Unknown Vendor"
}
documentation {
  description: "Stops a stopwatch service and returns the time elapsed."
}
options {
  supports_cancellation: false
  python_config {
    skill_module: "skills.stop_stopwatch.stop_stopwatch"
    proto_module: "skills.stop_stopwatch.stop_stopwatch_pb2"
    create_skill: "skills.stop_stopwatch.stop_stopwatch.StopStopwatch"
  }
}
dependencies {
  required_equipment {
    key: "stopwatch_service"
    value {
      capability_names: "stopwatch.StopwatchService"
    }
  }
}
parameter {
  message_full_name: "com.example.StopStopwatchParams"
  default_value {
    type_url: "type.googleapis.com/com.example.StopStopwatchParams"
  }
}
return_type {
  message_full_name: "com.example.StopStopwatchResult"
}
