id {
  package: "com.example"
  name: "say_skill_cc"
}
display_name: "Say skill"
vendor {
  display_name: "Intrinsic"
}
documentation {
  description: "Pause before logging a message."
}
options {
  supports_cancellation: true
  cc_config {
    create_skill: "::say_skill::SaySkill::CreateSkill"
  }
}
dependencies {
}
parameter {
  message_full_name: "com.example.SaySkillParams"
}
